yaffs2: switch from readlink_copy() to vfs_readlink()
To compile also as module. Fixes:

ERROR: modpost: "readlink_copy" [fs/yaffs2/yaffs.ko] undefined!

Signed-off-by: Mikko Rapeli <mikko.rapeli@linaro.org>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>